spring:

  application:
    name: otp-service

  profiles:
    active: local

  datasource:
    url: ${otp-service.datasource.url}
    username: ${otp-service.datasource.username}
    password: ${otp-service.datasource.password}
    hikari:
      schema: ${otp-service.datasource.schema}
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml


server:
  servlet:
    context-path: /otp/api/v1/otp

